server:
  port: 8081

logging:
  level:
    org:
    springframework: DEBUG


marcos:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
